# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/c8812/setup-makefiles.sh


PRODUCT_COPY_FILES += \
    vendor/huawei/c8812/proprietary/lib/libmmjpeg.so:obj/lib/libmmjpeg.so

PRODUCT_COPY_FILES += \
    vendor/huawei/c8812/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/huawei/c8812/proprietary/bin/rild:system/bin/rild \
    vendor/huawei/c8812/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/huawei/c8812/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/huawei/c8812/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/huawei/c8812/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/huawei/c8812/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/huawei/c8812/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/huawei/c8812/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/huawei/c8812/proprietary/lib/libhwrpc.so:system/lib/libhwrpc.so \
    vendor/huawei/c8812/proprietary/lib/libhwrpc.so:obj/lib/libhwrpc.so \
    vendor/huawei/c8812/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/huawei/c8812/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/huawei/c8812/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/huawei/c8812/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/huawei/c8812/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/huawei/c8812/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/huawei/c8812/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/huawei/c8812/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/huawei/c8812/proprietary/lib/libril.so:obj/lib/libril.so \
    vendor/huawei/c8812/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/huawei/c8812/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/huawei/c8812/proprietary/lib/libshareril.so:system/lib/libshareril.so \
    vendor/huawei/c8812/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/huawei/c8812/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/huawei/c8812/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/huawei/c8812/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/huawei/c8812/proprietary/lib/liboeminfo.so:system/lib/liboeminfo.so \
    vendor/huawei/c8812/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/huawei/c8812/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/huawei/c8812/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/huawei/c8812/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/huawei/c8812/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
    vendor/huawei/c8812/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/huawei/c8812/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/huawei/c8812/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/huawei/c8812/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/huawei/c8812/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/huawei/c8812/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/huawei/c8812/proprietary/lib/libOmxEvrcHwDec.so:system/lib/libOmxEvrcHwDec.so \
    vendor/huawei/c8812/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/huawei/c8812/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/huawei/c8812/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/huawei/c8812/proprietary/lib/libOmxOn2Dec.so:system/lib/libOmxOn2Dec.so \
    vendor/huawei/c8812/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/huawei/c8812/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/huawei/c8812/proprietary/lib/libOmxQcelpHwDec.so:system/lib/libOmxQcelpHwDec.so \
    vendor/huawei/c8812/proprietary/lib/libOmxrv9Dec.so:system/lib/libOmxrv9Dec.so \
    vendor/huawei/c8812/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/huawei/c8812/proprietary/lib/libOmxVp8Dec.so:system/lib/libOmxVp8Dec.so \
    vendor/huawei/c8812/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/huawei/c8812/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
    vendor/huawei/c8812/proprietary/bin/akmd8962:system/bin/akmd8962 \
    vendor/huawei/c8812/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/huawei/c8812/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
    vendor/huawei/c8812/proprietary/bin/compassd:system/bin/compassd \
    vendor/huawei/c8812/proprietary/bin/load_oemlogo:system/bin/load_oemlogo \
    vendor/huawei/c8812/proprietary/bin/modempre:system/bin/modempre \
    vendor/huawei/c8812/proprietary/bin/oem_rpc_svc:system/bin/oem_rpc_svc \
    vendor/huawei/c8812/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/huawei/c8812/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/huawei/c8812/proprietary/bin/rmt_oeminfo:system/bin/rmt_oeminfo \
    vendor/huawei/c8812/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/huawei/c8812/proprietary/bin/cust:system/bin/cust \
    vendor/huawei/c8812/proprietary/bin/write_NV_114:system/bin/write_NV_114 \
    vendor/huawei/c8812/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/huawei/c8812/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/huawei/c8812/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/huawei/c8812/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/huawei/c8812/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/huawei/c8812/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/huawei/c8812/proprietary/lib/libdsprofile.so:system/lib/libdsprofile.so \
    vendor/huawei/c8812/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/huawei/c8812/proprietary/lib/libuim.so:system/lib/libuim.so \
    vendor/huawei/c8812/proprietary/bin/hciattach:system/bin/hciattach \
    vendor/huawei/c8812/proprietary/lib/liboeminfodata.so:system/lib/liboeminfodata.so \
    vendor/huawei/c8812/proprietary/lib/libOmxIttiamVdec.so:system/lib/libOmxIttiamVdec.so \
    vendor/huawei/c8812/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/huawei/c8812/proprietary/lib/libhwnv.so:system/lib/libhwnv.so \
    vendor/huawei/c8812/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
    vendor/huawei/c8812/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/huawei/c8812/proprietary/lib/libloc_ext.so:system/lib/libloc_ext.so \
    vendor/huawei/c8812/proprietary/lib/libloc_api-rpc-qc.so:system/lib/libloc_api-rpc-qc.so \
    vendor/huawei/c8812/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/huawei/c8812/proprietary/lib/libmvs.so:system/lib/libmvs.so \
    vendor/huawei/c8812/proprietary/lib/libping_mdm.so:system/lib/libping_mdm.so \
	vendor/huawei/c8812/proprietary/lib/libcneapiclient.so:system/lib/libcneapiclient.so \
	vendor/huawei/c8812/proprietary/lib/libgetzip.so:system/lib/libgetzip.so \
	vendor/huawei/c8812/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so
#    vendor/huawei/c8812/proprietary/lib/hw/lights.msm7627a.so:system/lib/hw/lights.msm7627a.so \
