# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/u8818/setup-makefiles.sh
PRODUCT_COPY_FILES += \
    vendor/huawei/u8818/proprietary/lib/libhwrpc.so:obj/lib/libhwrpc.so
# RIL
PRODUCT_COPY_FILES += \
    vendor/huawei/u8818/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/huawei/u8818/proprietary/bin/rild:system/bin/rild \
    vendor/huawei/u8818/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/huawei/u8818/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/huawei/u8818/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/huawei/u8818/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/huawei/u8818/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/huawei/u8818/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/huawei/u8818/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/huawei/u8818/proprietary/lib/libhwrpc.so:system/lib/libhwrpc.so \
    vendor/huawei/u8818/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/huawei/u8818/proprietary/lib/libhwnv.so:obj/lib/libhwnv.so \
    vendor/huawei/u8818/proprietary/lib/libhwnv.so:system/lib/libhwnv.so \
    vendor/huawei/u8818/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/huawei/u8818/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/huawei/u8818/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/huawei/u8818/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/huawei/u8818/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/huawei/u8818/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/huawei/u8818/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/huawei/u8818/proprietary/lib/libril.so:obj/lib/libril.so \
    vendor/huawei/u8818/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/huawei/u8818/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/huawei/u8818/proprietary/lib/libshareril.so:system/lib/libshareril.so \
    vendor/huawei/u8818/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/huawei/u8818/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/huawei/u8818/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/huawei/u8818/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/huawei/u8818/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/huawei/u8818/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/huawei/u8818/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/huawei/u8818/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/huawei/u8818/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/huawei/u8818/proprietary/lib/libdsprofile.so:system/lib/libdsprofile.so \
    vendor/huawei/u8818/proprietary/lib/libuim.so:system/lib/libuim.so \
    vendor/huawei/u8818/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/huawei/u8818/proprietary/lib/libwiperjni.so:system/lib/libwiperjni.so \
    vendor/huawei/u8818/proprietary/lib/libwiperjni_v01.so:system/lib/libwiperjni_v01.so

# MIS
PRODUCT_COPY_FILES += \
    vendor/huawei/u8818/proprietary/lib/liboeminfo.so:system/lib/liboeminfo.so \
    vendor/huawei/u8818/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/huawei/u8818/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/huawei/u8818/proprietary/lib/liboeminfodata.so:system/lib/liboeminfodata.so \
    vendor/huawei/u8818/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/huawei/u8818/proprietary/lib/libaudioeq.so:system/lib/libaudioeq.so \
    vendor/huawei/u8818/proprietary/lib/hw/camera.msm7627a.so:system/lib/hw/camera.msm7627a.so
    
# MIS
PRODUCT_COPY_FILES += \
    vendor/huawei/u8818/proprietary/lib/hw/lights.msm7627a.so:system/lib/hw/lights.msm7627a.so
    
PRODUCT_COPY_FILES += \
    vendor/huawei/u8818/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/huawei/u8818/proprietary/lib/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
    vendor/huawei/u8818/proprietary/lib/libOmxAdpcmDec.so:system/lib/libOmxAdpcmDec.so \
    vendor/huawei/u8818/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/huawei/u8818/proprietary/lib/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
    vendor/huawei/u8818/proprietary/lib/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
    vendor/huawei/u8818/proprietary/lib/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
    vendor/huawei/u8818/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/huawei/u8818/proprietary/lib/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
    vendor/huawei/u8818/proprietary/lib/libOmxEvrcHwDec.so:system/lib/libOmxEvrcHwDec.so \
    vendor/huawei/u8818/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/huawei/u8818/proprietary/lib/libOmxIttiamVdec.so:system/lib/libOmxIttiamVdec.so \
    vendor/huawei/u8818/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/huawei/u8818/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/huawei/u8818/proprietary/lib/libOmxOn2Dec.so:system/lib/libOmxOn2Dec.so \
    vendor/huawei/u8818/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/huawei/u8818/proprietary/lib/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
    vendor/huawei/u8818/proprietary/lib/libOmxQcelpHwDec.so:system/lib/libOmxQcelpHwDec.so \
    vendor/huawei/u8818/proprietary/lib/libOmxrv9Dec.so:system/lib/libOmxrv9Dec.so \
    vendor/huawei/u8818/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/huawei/u8818/proprietary/lib/libOmxVp8Dec.so:system/lib/libOmxVp8Dec.so \
    vendor/huawei/u8818/proprietary/lib/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
    vendor/huawei/u8818/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \

PRODUCT_COPY_FILES += \
    vendor/huawei/u8818/proprietary/bin/akmd8962:system/bin/akmd8962 \
    vendor/huawei/u8818/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/huawei/u8818/proprietary/bin/compassd:system/bin/compassd \
    vendor/huawei/u8818/proprietary/bin/load_oemlogo:system/bin/load_oemlogo \
    vendor/huawei/u8818/proprietary/bin/modempre:system/bin/modempre \
    vendor/huawei/u8818/proprietary/bin/oem_rpc_svc:system/bin/oem_rpc_svc \
    vendor/huawei/u8818/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/huawei/u8818/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/huawei/u8818/proprietary/bin/rmt_oeminfo:system/bin/rmt_oeminfo \
    vendor/huawei/u8818/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/huawei/u8818/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/huawei/u8818/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/huawei/u8818/proprietary/lib/libping_mdm.so:system/lib/libping_mdm.so \
    vendor/huawei/u8818/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus

## Camera  LIB
PRODUCT_COPY_FILES += \
    vendor/huawei/u8818/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/huawei/u8818/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/huawei/u8818/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/huawei/u8818/proprietary/lib/libmmjpeg.so:obj/lib/libmmjpeg.so \
    vendor/huawei/u8818/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/huawei/u8818/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    vendor/huawei/u8818/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    vendor/huawei/u8818/proprietary/lib/libchromatix_mt9p017_ar.so:system/lib/libchromatix_mt9p017_ar.so \
    vendor/huawei/u8818/proprietary/lib/libchromatix_mt9p017_default_video.so:system/lib/libchromatix_mt9p017_default_video.so \
    vendor/huawei/u8818/proprietary/lib/libchromatix_mt9p017_preview.so:system/lib/libchromatix_mt9p017_preview.so \
    vendor/huawei/u8818/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
    vendor/huawei/u8818/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
    vendor/huawei/u8818/proprietary/lib/libchromatix_s5k4e1_ar.so:system/lib/libchromatix_s5k4e1_ar.so \
    vendor/huawei/u8818/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
    vendor/huawei/u8818/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
    vendor/huawei/u8818/proprietary/lib/libcommondefs.so:system/lib/libcommondefs.so \
    vendor/huawei/u8818/proprietary/lib/libcontrast.so:system/lib/libcontrast.so \
    vendor/huawei/u8818/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/huawei/u8818/proprietary/lib/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
    vendor/huawei/u8818/proprietary/lib/libmmitest.so:system/lib/libmmitest.so \
    vendor/huawei/u8818/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/huawei/u8818/proprietary/lib/libmmparser_divxdrmlib.so:system/lib/libmmparser_divxdrmlib.so \
    vendor/huawei/u8818/proprietary/lib/libmmparser.so:system/lib/libmmparser.so

## Camera  BIN
PRODUCT_COPY_FILES += \
    vendor/huawei/u8818/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/huawei/u8818/proprietary/bin/mm-qcamera-test:system/bin/mm-qcamera-test \
    vendor/huawei/u8818/proprietary/bin/mm-qcamera-testsuite-client:system/bin/mm-qcamera-testsuite-client \
    vendor/huawei/u8818/proprietary/bin/v4l2-qcamera-app:system/bin/v4l2-qcamera-app \
    vendor/huawei/u8818/proprietary/bin/mm-abl-daemon:system/bin/mm-abl-daemon \
    vendor/huawei/u8818/proprietary/bin/mm-abl-test:system/bin/mm-abl-test \
    vendor/huawei/u8818/proprietary/bin/mm-adec-omxaac-test:system/bin/mm-adec-omxaac-test \
    vendor/huawei/u8818/proprietary/bin/mm-adec-omxadpcm-test:system/bin/mm-adec-omxadpcm-test \
    vendor/huawei/u8818/proprietary/bin/mm-adec-omxamr-test:system/bin/mm-adec-omxamr-test \
    vendor/huawei/u8818/proprietary/bin/mm-adec-omxamrwb-test:system/bin/mm-adec-omxamrwb-test \
    vendor/huawei/u8818/proprietary/bin/mm-adec-omxevrc-hw-test:system/bin/mm-adec-omxevrc-hw-test \
    vendor/huawei/u8818/proprietary/bin/mm-adec-omxmp3-test:system/bin/mm-adec-omxmp3-test \
    vendor/huawei/u8818/proprietary/bin/mm-adec-omxQcelpHw-test:system/bin/mm-adec-omxQcelpHw-test \
    vendor/huawei/u8818/proprietary/bin/mm-adec-omxvam-test:system/bin/mm-adec-omxvam-test \
    vendor/huawei/u8818/proprietary/bin/mm-adec-omxwma-test:system/bin/mm-adec-omxwma-test \
    vendor/huawei/u8818/proprietary/bin/mm-adspsvc-test:system/bin/mm-adspsvc-test \
    vendor/huawei/u8818/proprietary/bin/mm-aenc-omxaac-test:system/bin/mm-aenc-omxaac-test \
    vendor/huawei/u8818/proprietary/bin/mm-aenc-omxamr-test:system/bin/mm-aenc-omxamr-test \
    vendor/huawei/u8818/proprietary/bin/mm-aenc-omxevrc-test:system/bin/mm-aenc-omxevrc-test \
    vendor/huawei/u8818/proprietary/bin/mm-aenc-omxqcelp13-test:system/bin/mm-aenc-omxqcelp13-test \
    vendor/huawei/u8818/proprietary/bin/mm-audio-alsa-test:system/bin/mm-audio-alsa-test \
    vendor/huawei/u8818/proprietary/bin/mm-audio-ctrl-test:system/bin/mm-audio-ctrl-test \
    vendor/huawei/u8818/proprietary/bin/mm-audio-mvs-test:system/bin/mm-audio-mvs-test \
    vendor/huawei/u8818/proprietary/bin/mm-audio-native-test:system/bin/mm-audio-native-test \
    vendor/huawei/u8818/proprietary/bin/mm-jpeg-dec-test:system/bin/mm-jpeg-dec-test \
    vendor/huawei/u8818/proprietary/bin/mm-jpeg-enc-test:system/bin/mm-jpeg-enc-test \
    vendor/huawei/u8818/proprietary/bin/mm-vdec-omx-test:system/bin/mm-vdec-omx-test \
    vendor/huawei/u8818/proprietary/bin/mm-venc-omx-test:system//bin/mm-venc-omx-test \
    vendor/huawei/u8818/proprietary/bin/brcm_patchram_plus_check:system/bin/brcm_patchram_plus_check \
    vendor/huawei/u8818/proprietary/bin/mm-audio-voem_if-test:system/bin/mm-audio-voem_if-test \
    vendor/huawei/u8818/proprietary/bin/oeminfo_test:system/bin/oeminfo_test \
    vendor/huawei/u8818/proprietary/bin/omx_tests:system/bin/omx_tests \
    vendor/huawei/u8818/proprietary/bin/test_gemini:system/bin/test_gemini

#add bin & .so
PRODUCT_COPY_FILES += \
	vendor/huawei/u8818/proprietary/bin/battery_charging:system/bin/battery_charging \
	vendor/huawei/u8818/proprietary/bin/cust:system/bin/cust \
	vendor/huawei/u8818/proprietary/lib/libwifidiag.so:system/lib/libwifidiag.so \
	vendor/huawei/u8818/proprietary/lib/libwifi_test.so:system/lib/libwifi_test.so
