# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/msm7x27a-common/setup-makefiles.sh

# share libs
PRODUCT_COPY_FILES += \
	vendor/huawei/msm7x30-common/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so

# bin files
PRODUCT_COPY_FILES += \
	vendor/huawei/msm7x30-common/proprietary/akmd8962:system/bin/akmd8962 \
	vendor/huawei/msm7x30-common/proprietary/akmd8975:system/bin/akmd8975 \
	vendor/huawei/msm7x30-common/proprietary/brcm_patchram_plus:system/bin/brcm_patchram_plus \
	vendor/huawei/msm7x30-common/proprietary/oem_rpc_svc:system/bin/oem_rpc_svc \
	vendor/huawei/msm7x30-common/proprietary/rmt_oeminfo:system/bin/rmt_oeminfo \
	vendor/huawei/msm7x30-common/proprietary/rmt_storage:system/bin/rmt_storage \
	vendor/huawei/msm7x30-common/proprietary/modempre:system/bin/modempre \
	vendor/huawei/msm7x30-common/proprietary/port-bridge:system/bin/port-bridge \
	vendor/huawei/msm7x30-common/proprietary/rild:system/bin/rild \
	vendor/huawei/msm7x30-common/proprietary/mediaserver:system/bin/mediaserver \
	vendor/huawei/msm7x30-common/proprietary/netmgrd:system/bin/netmgrd \
	vendor/huawei/msm7x30-common/proprietary/qmuxd:system/bin/qmuxd

# share libs
PRODUCT_COPY_FILES += \
	vendor/huawei/msm7x30-common/proprietary/libaudioeq.so:system/lib/libaudioeq.so \
	vendor/huawei/msm7x30-common/proprietary/camera.msm7x30.so:system/lib/hw/camera.msm7x30.so \
	vendor/huawei/msm7x30-common/proprietary/sensors.default.so:system/lib/hw/sensors.default.so \
	vendor/huawei/msm7x30-common/proprietary/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
	vendor/huawei/msm7x30-common/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
	vendor/huawei/msm7x30-common/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
	vendor/huawei/msm7x30-common/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
	vendor/huawei/msm7x30-common/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
	vendor/huawei/msm7x30-common/proprietary/libgsl.so:system/lib/libgsl.so \
	vendor/huawei/msm7x30-common/proprietary/libOpenVG.so:system/lib/libOpenVG.so \
	vendor/huawei/msm7x30-common/proprietary/libsc-a2xx.so:system/lib/libsc-a2xx.so \
	vendor/huawei/msm7x30-common/proprietary/libaudioalsa.so:system/lib/libaudioalsa.so \
	vendor/huawei/msm7x30-common/proprietary/libauth.so:system/lib/libauth.so \
	vendor/huawei/msm7x30-common/proprietary/libcm.so:system/lib/libcm.so \
	vendor/huawei/msm7x30-common/proprietary/libdiag.so:system/lib/libdiag.so \
	vendor/huawei/msm7x30-common/proprietary/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
	vendor/huawei/msm7x30-common/proprietary/libdsm.so:system/lib/libdsm.so \
	vendor/huawei/msm7x30-common/proprietary/libdsutils.so:system/lib/libdsutils.so \
	vendor/huawei/msm7x30-common/proprietary/libhwrpc.so:system/lib/libhwrpc.so \
	vendor/huawei/msm7x30-common/proprietary/libidl.so:system/lib/libidl.so \
	vendor/huawei/msm7x30-common/proprietary/libnetmgr.so:system/lib/libnetmgr.so \
	vendor/huawei/msm7x30-common/proprietary/libnv.so:system/lib/libnv.so \
	vendor/huawei/msm7x30-common/proprietary/liboeminfo.so:system/lib/liboeminfo.so \
	vendor/huawei/msm7x30-common/proprietary/liboem_rapi.so:system/lib/liboem_rapi.so \
	vendor/huawei/msm7x30-common/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
	vendor/huawei/msm7x30-common/proprietary/libpbmlib.so:system/lib/libpbmlib.so \
	vendor/huawei/msm7x30-common/proprietary/libqdi.so:system/lib/libqdi.so \
	vendor/huawei/msm7x30-common/proprietary/libqdp.so:system/lib/libqdp.so \
	vendor/huawei/msm7x30-common/proprietary/libqmi.so:system/lib/libqmi.so \
	vendor/huawei/msm7x30-common/proprietary/libqmiservices.so:system/lib/libqmiservices.so \
	vendor/huawei/msm7x30-common/proprietary/libqueue.so:system/lib/libqueue.so \
	vendor/huawei/msm7x30-common/proprietary/libril.so:system/lib/libril.so \
	vendor/huawei/msm7x30-common/proprietary/libril-qc-1.so:system/lib/libril-qc-1.so \
	vendor/huawei/msm7x30-common/proprietary/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
	vendor/huawei/msm7x30-common/proprietary/libwms.so:system/lib/libwms.so \
	vendor/huawei/msm7x30-common/proprietary/libwmsts.so:system/lib/libwmsts.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_mt9e013_ar.so:system/lib/libchromatix_mt9e013_ar.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_mt9e013_default_video.so:system/lib/libchromatix_mt9e013_default_video.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_mt9e013_preview.so:system/lib/libchromatix_mt9e013_preview.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_mt9e013_video_hfr.so:system/lib/libchromatix_mt9e013_video_hfr.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_mt9p012_ar.so:system/lib/libchromatix_mt9p012_ar.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_mt9p012_default_video.so:system/lib/libchromatix_mt9p012_default_video.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_mt9p012_km_default_video.so:system/lib/libchromatix_mt9p012_km_default_video.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_mt9p012_km_preview.so:system/lib/libchromatix_mt9p012_km_preview.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_mt9p012_preview.so:system/lib/libchromatix_mt9p012_preview.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_mt9t013_default_video.so:system/lib/libchromatix_mt9t013_default_video.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_mt9t013_preview.so:system/lib/libchromatix_mt9t013_preview.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_ov8810_default_video.so:system/lib/libchromatix_ov8810_default_video.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_ov8810_preview.so:system/lib/libchromatix_ov8810_preview.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_ov9726_preview.so:system/lib/libchromatix_ov9726_preview.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_ov9726_video.so:system/lib/libchromatix_ov9726_video.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_qs_s5k4e1_preview.so:system/lib/libchromatix_qs_s5k4e1_preview.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_qs_s5k4e1_video.so:system/lib/libchromatix_qs_s5k4e1_video.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_s5k3e2fx_default_video.so:system/lib/libchromatix_s5k3e2fx_default_video.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_s5k3e2fx_preview.so:system/lib/libchromatix_s5k3e2fx_preview.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_sn12m0pz_default_video.so:system/lib/libchromatix_sn12m0pz_default_video.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_sn12m0pz_preview.so:system/lib/libchromatix_sn12m0pz_preview.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_vb6801_default_video.so:system/lib/libchromatix_vb6801_default_video.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_vb6801_preview.so:system/lib/libchromatix_vb6801_preview.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_vx6953_default_video.so:system/lib/libchromatix_vx6953_default_video.so \
	vendor/huawei/msm7x30-common/proprietary/libchromatix_vx6953_preview.so:system/lib/libchromatix_vx6953_preview.so \
	vendor/huawei/msm7x30-common/proprietary/libgemini.so:system/lib/libgemini.so \
	vendor/huawei/msm7x30-common/proprietary/libmmipl.so:system/lib/libmmipl.so \
	vendor/huawei/msm7x30-common/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
	vendor/huawei/msm7x30-common/proprietary/liboemcamera.so:system/lib/liboemcamera.so
