# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/u8825d/setup-makefiles.sh


PRODUCT_COPY_FILES += \
    vendor/huawei/u8825d/proprietary/bin/abtfilt:system/bin/abtfilt \
    vendor/huawei/u8825d/proprietary/bin/akmd8963:system/bin/akmd8963 \
    vendor/huawei/u8825d/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/huawei/u8825d/proprietary/bin/ath_supplicant:system/bin/ath_supplicant \
    vendor/huawei/u8825d/proprietary/bin/bmgr:system/bin/bmgr \
    vendor/huawei/u8825d/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/huawei/u8825d/proprietary/bin/bt_check:system/bin/bt_check \
    vendor/huawei/u8825d/proprietary/bin/ccid_daemon:system/bin/ccid_daemon \
    vendor/huawei/u8825d/proprietary/bin/cust:system/bin/cust \
    vendor/huawei/u8825d/proprietary/bin/hciattach:system/bin/hciattach \
    vendor/huawei/u8825d/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/huawei/u8825d/proprietary/bin/load_oemlogo:system/bin/load_oemlogo \
    vendor/huawei/u8825d/proprietary/bin/loc_api_app:system/bin/loc_api_app \
    vendor/huawei/u8825d/proprietary/bin/mm-jpeg-enc-test-client:system/bin/mm-jpeg-enc-test-client \
    vendor/huawei/u8825d/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/huawei/u8825d/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/huawei/u8825d/proprietary/bin/mm-qcamera-testsuite-client:system/bin/mm-qcamera-testsuite-client \
    vendor/huawei/u8825d/proprietary/bin/modempre:system/bin/modempre \
    vendor/huawei/u8825d/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/huawei/u8825d/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/huawei/u8825d/proprietary/bin/oem_rpc_svc:system/bin/oem_rpc_svc \
    vendor/huawei/u8825d/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/huawei/u8825d/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/huawei/u8825d/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/huawei/u8825d/proprietary/bin/qrngd:system/bin/qrngd \
    vendor/huawei/u8825d/proprietary/bin/rild:system/bin/rild \
    vendor/huawei/u8825d/proprietary/bin/rmt_oeminfo:system/bin/rmt_oeminfo \
    vendor/huawei/u8825d/proprietary/bin/v4l2-qcamera-app:system/bin/v4l2-qcamera-app \
    vendor/huawei/u8825d/proprietary/bin/write_NV_114:system/bin/write_NV_114 \
    vendor/huawei/u8825d/proprietary/lib/hw/camera.msm7627a.so:system/lib/hw/camera.msm7627a.so \
    vendor/huawei/u8825d/proprietary/lib/hw/lights.msm7627a.so:system/lib/hw/lights.msm7627a.so \
    vendor/huawei/u8825d/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_imx105_sunny_default_video.so:system/lib/libchromatix_imx105_sunny_default_video.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_imx105_sunny_preview.so:system/lib/libchromatix_imx105_sunny_preview.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_mt9e013_default_video.so:system/lib/libchromatix_mt9e013_default_video.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_mt9e013_preview.so:system/lib/libchromatix_mt9e013_preview.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_mt9e013_video_hfr.so:system/lib/libchromatix_mt9e013_video_hfr.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_mt9p017_default_video.so:system/lib/libchromatix_mt9p017_default_video.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_mt9p017_preview.so:system/lib/libchromatix_mt9p017_preview.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_ov2720_hfr.so:system/lib/libchromatix_ov2720_hfr.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_ov2720_zsl.so:system/lib/libchromatix_ov2720_zsl.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_ov5647_default_video.so:system/lib/libchromatix_ov5647_default_video.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_ov5647_preview.so:system/lib/libchromatix_ov5647_preview.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_ov5647_video_hfr.so:system/lib/libchromatix_ov5647_video_hfr.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_s5k3h2_default_video.so:system/lib/libchromatix_s5k3h2_default_video.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_s5k3h2_preview.so:system/lib/libchromatix_s5k3h2_preview.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_s5k4e1_3_default_video.so:system/lib/libchromatix_s5k4e1_3_default_video.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_s5k4e1_3_preview.so:system/lib/libchromatix_s5k4e1_3_preview.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
    vendor/huawei/u8825d/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
    vendor/huawei/u8825d/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/huawei/u8825d/proprietary/lib/libCommandSvc.so:system/lib/libCommandSvc.so \
    vendor/huawei/u8825d/proprietary/lib/libCommon.so:system/lib/libCommon.so \
    vendor/huawei/u8825d/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/huawei/u8825d/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/huawei/u8825d/proprietary/lib/libdsprofile.so:system/lib/libdsprofile.so \
    vendor/huawei/u8825d/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/huawei/u8825d/proprietary/lib/libdsucsd.so:system/lib/libdsucsd.so \
    vendor/huawei/u8825d/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/huawei/u8825d/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/huawei/u8825d/proprietary/lib/libhwnv.so:system/lib/libhwnv.so \
    vendor/huawei/u8825d/proprietary/lib/libhwrpc.so:system/lib/libhwrpc.so \
    vendor/huawei/u8825d/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/huawei/u8825d/proprietary/lib/libifdsmartcardapi.so:system/lib/libifdsmartcardapi.so \
    vendor/huawei/u8825d/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/huawei/u8825d/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/huawei/u8825d/proprietary/lib/libimagesdk.so:system/lib/libimagesdk.so \
    vendor/huawei/u8825d/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
    vendor/huawei/u8825d/proprietary/lib/libloc_api-rpc-qc.so:system/lib/libloc_api-rpc-qc.so \
    vendor/huawei/u8825d/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/huawei/u8825d/proprietary/lib/libloc_ext.so:system/lib/libloc_ext.so \
    vendor/huawei/u8825d/proprietary/lib/liblocSDK_2.2.so:system/lib/liblocSDK_2.2.so \
    vendor/huawei/u8825d/proprietary/lib/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
    vendor/huawei/u8825d/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/huawei/u8825d/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/huawei/u8825d/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/huawei/u8825d/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/huawei/u8825d/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/huawei/u8825d/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/huawei/u8825d/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/huawei/u8825d/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/huawei/u8825d/proprietary/lib/libmmhttpstack.so:system/lib/libmmhttpstack.so \
    vendor/huawei/u8825d/proprietary/lib/libmmiipstreammmihttp.so:system/lib/libmmiipstreammmihttp.so \
    vendor/huawei/u8825d/proprietary/lib/libmmipstreamaal.so:system/lib/libmmipstreamaal.so \
    vendor/huawei/u8825d/proprietary/lib/libmmipstreamnetwork.so:system/lib/libmmipstreamnetwork.so \
    vendor/huawei/u8825d/proprietary/lib/libmmipstreamsourcehttp.so:system/lib/libmmipstreamsourcehttp.so \
    vendor/huawei/u8825d/proprietary/lib/libmmipstreamutils.so:system/lib/libmmipstreamutils.so \
    vendor/huawei/u8825d/proprietary/lib/libmmitest.so:system/lib/libmmitest.so \
    vendor/huawei/u8825d/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/huawei/u8825d/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/huawei/u8825d/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/huawei/u8825d/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/huawei/u8825d/proprietary/lib/libmvs.so:system/lib/libmvs.so \
    vendor/huawei/u8825d/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/huawei/u8825d/proprietary/lib/libNimsWrap.so:system/lib/libNimsWrap.so \
    vendor/huawei/u8825d/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/huawei/u8825d/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/huawei/u8825d/proprietary/lib/liboeminfo.so:system/lib/liboeminfo.so \
    vendor/huawei/u8825d/proprietary/lib/libOmxAacDec.so:system/lib/libOmxAacDec.so \
    vendor/huawei/u8825d/proprietary/lib/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
    vendor/huawei/u8825d/proprietary/lib/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
    vendor/huawei/u8825d/proprietary/lib/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
    vendor/huawei/u8825d/proprietary/lib/libOmxIttiamVdec.so:system/lib/libOmxIttiamVdec.so \
    vendor/huawei/u8825d/proprietary/lib/libOmxIttiamVenc.so:system/lib/libOmxIttiamVenc.so \
    vendor/huawei/u8825d/proprietary/lib/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
    vendor/huawei/u8825d/proprietary/lib/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
    vendor/huawei/u8825d/proprietary/lib/libOmxOn2Dec.so:system/lib/libOmxOn2Dec.so \
    vendor/huawei/u8825d/proprietary/lib/libOmxQcelp13Dec.so:system/lib/libOmxQcelp13Dec.so \
    vendor/huawei/u8825d/proprietary/lib/libOmxrv9Dec.so:system/lib/libOmxrv9Dec.so \
    vendor/huawei/u8825d/proprietary/lib/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
    vendor/huawei/u8825d/proprietary/lib/libOmxVp8Dec.so:system/lib/libOmxVp8Dec.so \
    vendor/huawei/u8825d/proprietary/lib/libOmxWmvDec.so:system/lib/libOmxWmvDec.so \
    vendor/huawei/u8825d/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/huawei/u8825d/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/huawei/u8825d/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/huawei/u8825d/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/huawei/u8825d/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/huawei/u8825d/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/huawei/u8825d/proprietary/lib/libqmi_csvt_srvc.so:system/lib/libqmi_csvt_srvc.so \
    vendor/huawei/u8825d/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/huawei/u8825d/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/huawei/u8825d/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/huawei/u8825d/proprietary/lib/libril-qc-1-no-dsds.so:system/lib/libril-qc-1-no-dsds.so \
    vendor/huawei/u8825d/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/huawei/u8825d/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/huawei/u8825d/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/huawei/u8825d/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/huawei/u8825d/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/huawei/u8825d/proprietary/lib/libzy_imgdenoise.so:system/lib/libzy_imgdenoise.so
